"use client";
import Chapters from "@/app/ui/components/chapters";
import PhotoBar from "@/app/ui/Sections/photobar";
import Image from "next/image";

export default function page() {
    const path = [
        {
            name: "główna",
            url: "/",
        },
        {
            name: "historia szkoły",
        }
    ]

    return (
        <div className="flex gap-2">
            <div className="text-custom-gray-300 w-full ">
                <PhotoBar path={path}/>
                <div className="max-w-4xl mx-auto">
                    <h2 className="text-2xl font-bold py-2 text-custom-gray-200" id="historia-szkoly">Historia szkoły</h2>
                    <div className="mx-6">

                    <p>
                        Wrzesień 1945 r. &#8211; na terenie miasta Rawy została otwarta Publiczna Dokształcająca Szkoła Zawodowa. Szkołę umieszczono w budynku Szkoły Podstawowej w Rawie Mazowieckiej przy ulicy Kościuszki 19. Zajęcia lekcyjne odbywały się w godzinach popołudniowych. Szkoła była typu ogólnozawodowego. W szkole zawodowej prowadzone były następujące przedmioty: j.polski, j.obcy, religia, chemia, historia, nauka o Polsce i świecie współczesnym, higiena, organizacja zakładu pracy i rachunkowość.<br/>W roku 1945/1946 szkoła liczy 44 uczniów w tym 8 dziewcząt; w 1946/1947 szkoła liczy 94 uczniów w tym 19 dziewcząt; w 1947/1948 93 uczniów w tym 25 dziewcząt. W czerwcu 1948 opuścili mury szkoły pierwsi absolwenci w liczbie 6 osób. Poczet absolwentów otwiera Leon Oczakowski zapisany w księdze absolwentów pod pozycją nr 1.<br/>Dyrektorem szkoły z dniem 1.09.1945 został nauczyciel miejscowej szkoły podstawowej &#8211; Stefan Piotrowski. Był on jedynym etatowym nauczycielem Szkoły Zawodowej Dokształcającej, pozostali nauczyciele pracowali w niepełnym wymiarze godzin.<br/>Publiczna Dokształcająca Szkoła Zawodowa w Rawie Mazowieckiej istniała 3 lata.
                    </p>
                    <Image src="/historia-szkoly/1.jpg" className="mx-auto rounded-md overflow-hidden my-5" alt="1 - historia szkoły" width={650} height={435}/>
                    <p>Dnia 1.09.1948 zgodnie z rozporządzeniem Ministra Oświaty szkoła zmienia nazwę na &#8222;Publiczną Średnią Szkołę Zawodową&#8221; w Rawie Mazowieckiej. Szkoła ta nadal mieści się w budynku Szkoły Podstawowej przy ul. Kościuszki 19. Szkoła posiada jeden pokój z przeznaczeniem na kancelarię, bibliotekę i gabinet dyrektora oraz po południu używa się 6 izb lekcyjnych z przeznaczeniem na zajęcia lekcyjne. W latach 1948-1952 Publiczną Średnią Szkołę Zawodową ukończyło 75 uczniów, z tego 25 dziewcząt; Zasadniczą Szkołę Zawodową ukończyło 49 uczniów w tym 24 dziewczęta.<br/>Dnia 1.09.1949 roku szkoła wynajęła izbę przy ul.Rasumowskiego 15 na szkolny warsztat krawiectwa damskiego.<br/>Od dnia 1.09.1950 roku dyrektorem szkoły zostaje J.Krzyżanowski, nauczyciel miejscowej szkoły podstawowej, który pełni tę funkcję do dnia 31.03.1952 r. Od 1.04.1952 do 31.08.1952 funkcję dyrektora pełni Stanisław Jadczak.<br/>Od 1.09.1950 r. obok Publicznej Średniej Szkoły Zawodowej w 3 letnim cyklu kształcenia &#8211; organizuje się klasy 2-letnie Zasadniczej Szkoły Metalowej.<br/>Publiczna Średnia Szkoła Zawodowa w Rawie Mazowieckiej wygasa z dniem 31.08.1952, a rozwija się Zasadnicza Szkoła Metalowa. Od 1.09.1952r. funkcję dyrektora Zasadniczej Szkoły Metalowej, a następnie Szkoły Przysposobienia Zawodowego pełni Bogdan Spychała.<br/>Od 1952 szkoła szkoli tylko w jednej specjalności &#8211; ślusarz maszyn rolniczych. Kierunek ten wygasa w roku 1957-1958 a wprowadza się kierunek &#8211; ślusarz. Od 1.09.1958 r. zostaje zmieniona nazwa szkoły na &#8222;Zasadniczą Szkołę Zawodową&#8221; w Rawie Mazowieckiej. Zmian jest podyktowana wprowadzeniem nowych kierunków kształcenia.<br/>Od 1.09.1959 obok Zasadniczej Szkoły Zawodowej, w tych samych budynkach o wspólnej administracji kierowniczej powstaje 2-letnia Szkoła Przysposobienia Zawodowego o specjalności: metalowy i odzieżowo-włokienniczy.<br/>Od 1.09.1953 Zasadnicza Szkoła Metalowa zajęła po liceum rawskim budynek przy ulicy Warszawskiej 16, który przeznaczono na budynek szkolny. Pozostałe budynki (Świerczewskiego 9 i Kościuszki 9) przeznaczono na zorganizowanie internatu.&nbsp;</p>
                    <Image src="/historia-szkoly/2.jpg" className="mx-auto rounded-md overflow-hidden my-5" alt="2 - historia szkoły" width={650} height={435}/>
                    <p>W 1954 r. dyrektor szkoły zaczął czynić starania o budowę nowej szkoły. Została opracowana dokumentacja projektowo-kosztorysowa, plac szkoła otrzymała od Prezydium Miejskiej Rady Narodowej w Rawie Mazowieckiej. Był to 3 hektarowy plac przy ulicy Tomaszowskiej. Budowa miała być rozpoczęta w 1955 r. Ze względu na trudną sytuację gospodarczą kraju odebrano szkole plac na którym rozpoczęto budowę osiedla mieszkaniowego. W 1959 r. w Ministerstwie Oświaty zdecydowano o budowie zespołu budynków dla Szkoły Zawodowej przy ul.Ludowej 46. W roku 1962 ruszyły pierwsze prace budowlane.<br/>Dnia 1.09.1962r. zlikwidowano drugą (obok Zasadniczej Szkoły Zawodowej) Szkołę Przysposobienia Zawodowego a zorganizowano pełną szkołę średnią Technikum Mechaniczne o specjalności: aparatura kontrolno-pomiarowa i automatyka przemysłowo-mechaniczna.<br/>W marcu 1962 rozpoczyna się budowa budynku szkolnego. Budowa trwa trzy lata. Dnia 19.09.1965r. nowy budynek zostaje przez komisję odebrany i przekazany szkole do użytkowania. Budynek jest 3-kondygnacyjny, obok budynku jest boisko szkolne. Koszt budynku wyniósł 5.642.000 starych złotych, a wraz z wyposażeniem i dodatkowymi kosztami &#8211; 9.059.700 starych złotych.<br/>W nowy budynku szkoła otrzymała w sumie 50 pomieszczeń.</p>
                    <Image src="/historia-szkoly/3.jpg" className="mx-auto rounded-md overflow-hidden my-5" alt="3 - historia szkoły" width={650} height={435}/>
                    <p>Rok 1963: rozpoczęto budowę nowego budynku internatu. Budowa trwała 3 lata-komisyjnie odebrano budynek internatu 13.04.1966r. Pierwszym kierownikiem internatu został Jan Kolizda.</p>
                    <Image src="/historia-szkoly/4.jpg" className="mx-auto rounded-md overflow-hidden my-5" alt="4 - historia szkoły" width={650} height={435}/>
                    <p>Rok 1964: rozpoczęto budowę warsztatu na placu przy ulicy ludowej. Budowa trwała dwa lata. Budynek odebrano 14.10.1966r.</p>
                    <Image src="/historia-szkoly/warsztat.jpg" className="mx-auto rounded-md overflow-hidden my-5" alt="5 - historia szkoły" width={650} height={435}/>
                    <p>W roku 1966 z Zasadniczej Szkoły Zawodowej wydzielono 4 oddziały o specjalności odzieżowej i utworzono w starym budynku ZSZ przy ulicy Warszawskiej 16 samodzielną Zasadniczą Szkołę Odzieżową. W grudniu 1971 r. Zasadnicza Szkoła Odzieżowa przeniesiona została do budynku Technikum Mechanicznego i Zasadniczej Szkoły Zawodowej. Dotychczas zajmowany budynek przy ul.Warszawskiej 16 został oddany do remontu, a następnie przeznaczony na warsztaty odzieżowe.<br/>We wrześniu 1977r. nastąpiło połączenie szkół zawodowych w wyniku którego powstał Zespół Szkół Zawodowych. Od tego momentu w jednym budynku przy ulicy ludowej 46 młodzież kształci się w zawodzie:<br/>Technikum Mechaniczne:do 1975r. &#8211; aparatura kontrolno-pomiarowa i mechaniczna automatyka przemysłowa,<br/>od 1976r. &#8211; naprawa i eksploatacja pojazdów samochodowych.</p>
                    <p><br/>Liceum Zawodowe &#8211; obróbka skrawaniem<br/>Szkoła Zawodowa:tokarz,<br/>ślusarz-mechanik,<br/>mechanik-kierowca pojazdów samochodowych,<br/>elektomechanik pojazdów samochodowych,<br/>mechanik maszyn rolniczych,<br/>krawiec odzieży damskiej lekkiej,<br/>krawiec-szwacz,<br/>naprawa urządzeń przemysłowych,<br/>kierunek wielozawodowy.</p>
                    <p><br/>W roku szkolnym 1982/1983 odszedł na emeryturę dotychczasowy dyrektor szkoły mgr inż. Wiesław Adamski. Funkcję dyrektora pełnił od roku 1974. Nowym dyrektorem szkoły mianowany został pełniący uprzednio funkcję zastępcy<br/>mgr Mirosław Górecki.<br/>W 1987/1988 Zespół Szkół Zawodowych nr1. w Rawie Mazowieckiej składa się z Zasadniczej Szkoły Zawodowej, Technikum Samochodowego, Technikum Mechanicznego, Technikum Mechanicznego zaocznego i Technikum Odzieżowego Zaocznego. W całym zespole szkół uczy się łącznie 1140 uczniów i pracuje 71 nauczycieli pełnozatrudnionych i 28 niepełnozatrudnionych.<br/>W 1988/89 w szkole pracuje 102 nauczycieli i uczy się 1260 uczniów. W roku 1989/1990 nauka odbywa się w 49 klasach (5 klas Technikum Samochodowego, 5 klas Technikum Mechanicznego, 31 klas zasadniczych, 2 klasy OHP, 3 klasy Technikum Samochodowego zaocznego i 3 klasy Technikum Odzieżowego zaocznego).<br/>Dnia 23 grudnia 1991 roku dyrektorem Zespołu Szkół Zawodowych w Rawie Mazowieckiej zostaje<br/>mgr Bogumiła Papis.<br/>Dzień 9 listopad 1997 to smutna data w historii naszej szkoły, śmiercią tragiczną odchodzi od nas Pani Dyrektor Bogumiła Papis. Od 3 lutego 1998 roku funkcję dyrektora szkoły pełni mgr Stanisław Borek. Z dniem 1 września 2000 roku następuje zmiana nazwy szkoły. Od tej daty (do chwili obecnej) pełna nazwa szkoły brzmi:</p>
                    <p>Zespół Szkół &#8211; Centrum Edukacji Zawodowej i Ustawicznej w Rawie Mazowieckiej.</p>
                    <p>Od 1 września 2002 funkcję dyrektora szkoły obejmuje mgr Marek Dobek.</p>
                    <p>Dnia 17 października 2003 roku został uruchomiony szkolny serwer www i ftp &#8211; administratorem serwera jest Krzysztof Gruchała, nauczyciel informatyki i matematyki.</p>
                    <p>Dnia 14 maja 2004 odbyła się uroczystość nadania imienia. Od tego dnia pełna nazwa szkoły brzmi: Zespół Szkół &#8211; Centrum Edukacji Zawodowej i Ustawicznej w Rawie Mazowieckiej im.Mikołaja Kopernika.</p>
                    <p>Dnia 12.10.2004 szkoła uzyskała tytuł &#8222;Szkoły z klasą&#8221; w konkursie organizowanym przez Gazetę Wyborczą, pod patronatem Prezydenta Rzeczypospolitej Polskiej.</p>
                    <p>Od dnia 01.09.2007 funkcję dyrektora szkoły obejmuje mgr Radosław Kaźmierczak.</p>
                    </div>
                </div>
            </div>
        </div>
    )
}